---
title: "Leaflet Examples"
author: "Geoffrey Arnold"
date: "9/5/2018"
output: html_document
---


```{r setup, include=FALSE}
require(rgdal)
require(leaflet)
require(leaflet.extras)

require(dplyr)
require(readxl)
require(stringr)
```

# Getting Spatial Data

```{r, loading}
cds.load <- readOGR("./cb_2015_us_cd114_500k/cb_2015_us_cd114_500k.shp", layer = "cb_2015_us_cd114_500k", GDAL1_integer64_policy = TRUE)
plot(cds.load)

polls <- readOGR("Allegheny_County_Polling_Place_Locations_November_2016.geojson")
plot(polls)
```

# Merging Table Data to your shapefile

```{r, merging}
op_data <- read_excel("Geographies_of_Opportunity_Ranking_Well_Being_by_Congressional_District_(114th_Congress).xlsx") %>%
  mutate(Number = str_pad(Number, 4, pad = "0"))

# Just having the matching GEOID's
cds <- cds.load[cds.load$GEOID %in% op_data$Number,]

cds@data <- merge(cds@data, op_data, sort = FALSE, by.x = "GEOID", by.y = "Number")
```

# Blank map with basemap

```{r}
leaflet() %>%
  addProviderTiles(providers$Esri.WorldImagery)
```

# Blank map with no warp

```{r}
leaflet() %>%
  addProviderTiles(providers$Esri.WorldImagery, options = providerTileOptions(noWrap = TRUE))
```

# Shape

```{r, polygon}

```

# Lines

```{r, lines}
rivers <- readOGR("./ne_10m_rivers_lake_centerlines")

leaflet(data = rivers) %>%
  addProviderTiles("Esri.WorldTerrain", options = providerTileOptions(noWrap = TRUE)) %>%
  addPolylines(color = "#63CBD3")
```

# Line with Popups

```{r, popups}
rivers <- readOGR("./ne_10m_rivers_lake_centerlines")
plot(rivers)

leaflet(data = rivers) %>%
  addProviderTiles("Esri.WorldTerrain", options = providerTileOptions(noWrap = TRUE)) %>%
  addPolylines(color = "#63CBD3", popup = ~name_en)
```

# Points

## Circle Markers

```{r, markers}
potholes <- read.csv("311_potholes.csv")

# Custom Palette
pal311 <- colorFactor(c("#d73027", "#1a9850"), c("Closed", "Open"))

leaflet() %>%
  addProviderTiles("OpenStreetMap.HOT") %>%
  addCircleMarkers(data = potholes, lng = ~X, lat = ~Y, radius = 1.5, color = ~pal311(STATUS)) %>%
  addLegend(position = "topright" , pal = pal311, values = potholes$STATUS, title = "Status")
```

## Points from GEOJSON

```{r, geojson}
leaflet(data = polls) %>%
  addProviderTiles("OpenStreetMap.Mapnik") %>%
  addMarkers(popup = ~paste0(LocName, ": ", NewAddress, " ", City, " PA ", Zip))
```

## Points Awesome Markers

```{r, awesome_markers}
potOver <- read.csv("potholesOvergrowth.csv")

icons <- awesomeIconList(
  Potholes = makeAwesomeIcon(icon = "road", library = "fa", markerColor = "gray"),
  Overgrowth = makeAwesomeIcon(icon = "leaf", library = "fa", markerColor = "green")
)

leaflet(data = potOver) %>%
  addProviderTiles("OpenStreetMap.HOT") %>%
  addAwesomeMarkers(lng = ~X, lat = ~Y, icon = ~icons[REQUEST_TYPE], popup = ~REQUEST_TYPE)
```
